export const overviewStats = {
  totalEmployees: 48,
  productiveHours: "1,240h",
  idleHours: "310h",
  distractionHours: "185h",
  automationOpportunities: 12,
  estimatedMonthlySavings: "$8,500",
};

export const employees = [
  {
    id: 1,
    name: "Rahul Sharma",
    role: "Data Entry Operator",
    productiveHours: 32,
    idleHours: 5,
    distractionTime: 3,
    riskLevel: "Low",
    workPercentage: 80,
    distractionPercentage: 20,
    idlePercentage: 12, // overall out of 40
    activePercentage: 88,
    topApps: ["Excel", "Internal CRM", "Outlook"],
    topWebsites: ["google.com", "youtube.com (Music)"],
    repetitiveTasks: ["Invoice Data Entry", "Daily Report Generation"],
    automationIdeas: ["OCR for Invoices", "Automated Daily Summary Script"],
  },
  {
    id: 2,
    name: "Priya Verma",
    role: "HR Executive",
    productiveHours: 28,
    idleHours: 8,
    distractionTime: 4,
    riskLevel: "Medium",
    workPercentage: 70,
    distractionPercentage: 30,
    idlePercentage: 20,
    activePercentage: 80,
    topApps: ["Workday", "LinkedIn", "Teams"],
    topWebsites: ["linkedin.com", "facebook.com"],
    repetitiveTasks: ["Screening Resumes", "Scheduling Interviews"],
    automationIdeas: ["AI Resume Parser", "Calendar Auto-Scheduler"],
  },
  {
    id: 3,
    name: "Aman Gupta",
    role: "Support Executive",
    productiveHours: 25,
    idleHours: 10,
    distractionTime: 5,
    riskLevel: "High",
    workPercentage: 62,
    distractionPercentage: 38,
    idlePercentage: 25,
    activePercentage: 75,
    topApps: ["Zendesk", "Slack", "Chrome"],
    topWebsites: ["twitter.com", "reddit.com"],
    repetitiveTasks: ["Password Resets", "Basic FAQ Responses"],
    automationIdeas: ["AI Chatbot for FAQs", "Automated Password Reset Flow"],
  },
  {
    id: 4,
    name: "Neha Singh",
    role: "Accountant",
    productiveHours: 35,
    idleHours: 3,
    distractionTime: 2,
    riskLevel: "Low",
    workPercentage: 87,
    distractionPercentage: 13,
    idlePercentage: 7,
    activePercentage: 93,
    topApps: ["QuickBooks", "Excel", "Tally"],
    topWebsites: ["incometax.gov.in", "moneycontrol.com"],
    repetitiveTasks: ["Reconciling Bank Statements", "Vendor Payments"],
    automationIdeas: ["Bank Statement Auto-Reconciliation", "Scheduled Bulk Payments"],
  },
];

export const reports = [
  {
    id: 1,
    title: "Distraction Report",
    description: "Detailed analysis of non-work related applications and websites used during work hours.",
    status: "Ready",
  },
  {
    id: 2,
    title: "Work Pattern Report",
    description: "Insights into peak productivity hours, average focus time, and meeting overhead.",
    status: "Ready",
  },
  {
    id: 3,
    title: "Automation Proposal Report",
    description: "AI-generated list of highly repetitive tasks and proposed automation strategies.",
    status: "Generating...",
  },
];

export const automationTasks = [
  {
    id: 1,
    taskName: "Invoice Data Entry",
    employee: "Rahul Sharma",
    timeSavedPerWeek: "15 hours",
    estimatedMonthlySaving: "$1,200",
    difficulty: "Medium",
  },
  {
    id: 2,
    taskName: "Screening Resumes",
    employee: "Priya Verma",
    timeSavedPerWeek: "10 hours",
    estimatedMonthlySaving: "$1,500",
    difficulty: "Complex",
  },
  {
    id: 3,
    taskName: "Password Resets",
    employee: "Aman Gupta",
    timeSavedPerWeek: "8 hours",
    estimatedMonthlySaving: "$800",
    difficulty: "Simple",
  },
  {
    id: 4,
    taskName: "Bank Statement Auto-Reconciliation",
    employee: "Neha Singh",
    timeSavedPerWeek: "12 hours",
    estimatedMonthlySaving: "$2,000",
    difficulty: "Medium",
  },
];
